<?php

namespace Lack\Invoice\Format;

class ImageCol extends Col
{
    public function __construct(int $width, public string $image, public ?int $imgwidth=null)
    {
        parent::__construct($width);
    }

    public function render(ColumnFpdf $fpdf, int $width)
    {
        $fpdf->Image($this->image);
        parent::render($fpdf, $width); // TODO: Change the autogenerated stub
    }
}
